-----
- hosts: localhost
  become: yes
  tasks:
         
          
          - name: deploying war into tomcat server
            copy:
                    src: /var/lib/jenkins/workspace/Project1/project_package_phase/target/addressbook-2.0.war
                    dest: /usr/local/latest/webapps
                    remote_src: yes
          - name: Copying war file
            command: cp /var/tmp/workspace/Ansible_pipeline/ansible_package_phase/target/addressbook-2.0.war /usr/local/latest/webapps/
          - name: Starting Tomcat
            command: sh /usr/local/latest/bin/startup.sh
            become: yes
